//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q41.DocumentService.TemplateManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionStrings
    {
        public ConnectionStrings()
        {
            this.ProcedureCalls = new HashSet<ProcedureCalls>();
        }
    
        public string Name { get; set; }
        public string Value { get; set; }
        public int DbmsType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<ProcedureCalls> ProcedureCalls { get; set; }
    }
}
