//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q41.DocumentService.TemplateManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureCalls
    {
        public int ProcedureCallId { get; set; }
        public string SchemaName { get; set; }
        public string PackageName { get; set; }
        public string ProcedureName { get; set; }
        public string ConnectionStringName { get; set; }
        public int DbmsType { get; set; }
        public string Paramaters { get; set; }
        public string ResultFields { get; set; }
        public string NewParametarName { get; set; }
        public string NewCursorName { get; set; }
        public string ProcedureParameters { get; set; }
        public bool Complex { get; set; }    
        public virtual ConnectionStrings ConnectionStrings { get; set; }
    }
}
