//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q41.DocumentService.TemplateManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateGroups
    {
        public TemplateGroups()
        {
            this.Templates = new HashSet<Templates>();
        }
    
        public int TemplateGroupId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
    
        public virtual ICollection<Templates> Templates { get; set; }
    }
}
