//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q41.DocumentService.TemplateManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMapiranja
    {
        public int TemplateDataSourceId { get; set; }
        public string Identifikator { get; set; }
        public string Predlozak { get; set; }
        public string Procedura { get; set; }
    }
}
