//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q41.DocumentService.TemplateManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProcedureCalls
    {
        public int ProcedureCallId { get; set; }
        public string SchemaName { get; set; }
        public string PackageName { get; set; }
        public string ProcedureName { get; set; }
        public string ConnectionStringName { get; set; }
        public int DbmsType { get; set; }
        public string Paramaters { get; set; }
        public string ResultFields { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> CSDbmsType { get; set; }
        public Nullable<long> RBr { get; set; }
        public string ResultFieldsText { get; set; }
        public Nullable<int> Ukupno { get; set; }
        public string ddlProcedureName { get; set; }
    }
}
